project:
  type: website
  output-dir: _site
  pre-render: python scripts/generate_materials_overview.py
metadata-files:
  - course.yml
website:
  title: "Introduction to Programming"
  repo-url: "{{< meta repository.url >}}"
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Objectives
        href: objectives.qmd
      - text: Teaching notes
        href: teaching_notes.qmd
      - text: Materials
        href: materials.qmd

format:
  html:
    theme: cosmo
    toc: false
    css:
      - assets/styles.css
    include-after-body: assets/repo-actions-bottom.html
    grid:
      sidebar-width: 280px
      body-width: 1000px
      margin-width: 280px
      gutter-width: 1.5rem


format-links: false

bibliography: references.bib
execute:
  freeze: auto
