project:
  type: default
  output-dir: ../_site/exercises
profile:
  default: assign
quarto-required: ">=1.8.0"
filters:
  - ../scripts/mermaid_style.lua
format:
  html:
    css:
      - ../assets/mermaid.css
  ipynb: default
execute:
  fig-align: center
